// Données de référence des 15 indicateurs : source unique pour la matrice,
// le tableau méthodologique final et les fiches, afin de garantir leur cohérence.
const { r, sb, ss, fr, sum, M, w0 } = require('./mathh');

const DV = 'Disponibilité de la série à vérifier.';

const AXES = [
  { n: 1, nom: 'Souveraineté alimentaire', court: 'Souveraineté alimentaire' },
  { n: 2, nom: 'Compétitivité de l\'agriculture', court: 'Compétitivité' },
  { n: 3, nom: 'Accès au financement agricole', court: 'Financement agricole' },
  { n: 4, nom: 'Sécurisation du foncier rural', court: 'Foncier rural' },
  { n: 5, nom: 'Durabilité des systèmes de production', court: 'Durabilité' },
];

const IND = [
  // ───────────────────────── AXE 1
  {
    axe: 1, k: 1, code: 'TC', dim: 'Autonomie alimentaire',
    nom: 'Taux de couverture des besoins alimentaires par la production nationale',
    sens: 'Hausse',
    finalite: 'Mesurer le degré d\'autonomie alimentaire du pays, c\'est-à-dire la part de la consommation alimentaire nationale couverte par la production nationale.',
    question: 'Dans quelle proportion la production nationale couvre-t-elle la consommation alimentaire apparente de la Côte d\'Ivoire ?',
    definition: 'Moyenne pondérée, sur un panier alimentaire ivoirien commun, des rapports entre production nationale et consommation apparente de chaque produit, les pondérations correspondant à la part fixe de chaque produit dans l\'apport calorique du panier au cours de la période de référence.',
    formuleTxt: 'TC_{t} = Σ_{i} w_{i}^{0} × TC_{i,t}, avec TC_{i,t} = P_{i,t} / C_{i,t} × 100 et C_{i,t} = P_{i,t} + M_{i,t} − X_{i,t} ± ΔStocks_{i,t}',
    math: () => [M(sb('TC', 't'), '=', sum('i', [w0(), sb('TC', 'i,t')]), ',   ', sb('TC', 'i,t'), '=', fr(sb('P', 'i,t'), sb('C', 'i,t')), '×100')],
    numerateur: 'Production nationale du produit i, exprimée au même stade que la consommation (équivalent produit).',
    denominateur: 'Consommation apparente du produit i : production + importations − exportations ± variation des stocks.',
    variables: 'Par produit et par année : production (P), importations (M), exportations (X), variation des stocks, coefficients de conversion entre stades de produit, teneur calorique ; consommation de la période de référence pour le calcul des poids.',
    unite: '%',
    frequence: 'Annuelle',
    srcP: 'Bilans alimentaires FAOSTAT ; statistiques nationales de production végétale, animale et halieutique.',
    srcS: 'Statistiques du commerce extérieur (douanes, ANStat) ; UN Comtrade ; EHCVM pour la structure de consommation.',
    dispo: 'Les bilans alimentaires FAOSTAT couvrent la Côte d\'Ivoire selon la méthodologie révisée à compter de 2010 ; années et produits effectivement couverts sur 2015-2025 : ' + DV.toLowerCase() + ' Série nationale consolidée : ' + DV.toLowerCase(),
    agregation: 'Moyenne arithmétique pondérée des taux par produit, à poids fixes (logique de Laspeyres).',
    ponderations: 'Part de chaque produit dans les calories totales du panier, calculée sur une moyenne pluriannuelle de référence puis maintenue fixe.',
    precautions: 'Exprimer production et consommation au même stade (par exemple riz usiné et non paddy) avec des coefficients de conversion documentés ; appliquer une convention unique pour les stocks ; conserver dans le panier les produits consommés mais non produits localement, dont le taux est nul.',
    limites: 'La consommation apparente est sensible aux erreurs sur la production vivrière et aux flux transfrontaliers non enregistrés ; l\'excédent d\'un produit compense le déficit d\'un autre ; l\'indicateur ne renseigne ni l\'accès des ménages ni la qualité nutritionnelle.',
    comparabilite: 'Proche du taux d\'autosuffisance (self-sufficiency ratio) de la FAO pour chaque produit ; le niveau agrégé, pondéré par la structure de consommation ivoirienne, n\'est pas directement comparable entre pays.',
    observations: 'Composition du panier, période de référence et traitement analytique des taux supérieurs à 100 % à arrêter formellement.',
    reference: 'FAO (2001), Food Balance Sheets – A Handbook ; Clapp (2017), Food Policy, 66.',
    travaux: 'Arrêter la liste des produits du panier et le seuil de couverture calorique visé ; fixer la période de référence ; documenter les coefficients de conversion et les teneurs caloriques ; rapprocher séries FAOSTAT et nationales ; tester la sensibilité à un plafonnement des taux à 100 %.',
  },
  {
    axe: 1, k: 2, code: 'IPVH', dim: 'Capacité productive',
    nom: 'Indice de production vivrière par habitant',
    sens: 'Hausse',
    finalite: 'Apprécier si la production alimentaire nationale progresse au moins aussi vite que la population.',
    question: 'La production vivrière par habitant augmente-t-elle par rapport à la période de référence ?',
    definition: 'Indice pondéré des productions par habitant des produits du panier alimentaire commun, rapportées à leur niveau moyen de la période de référence (base 100), avec les pondérations caloriques du taux de couverture.',
    formuleTxt: 'IPVH_{t} = Σ_{i} w_{i}^{0} × I_{i,t}, avec I_{i,t} = (P_{i,t} / N_{t}) / (P̄_{i}^{0} / N̄^{0}) × 100',
    math: () => [M(sb('IPVH', 't'), '=', sum('i', [w0(), sb('I', 'i,t')]), ',   ', sb('I', 'i,t'), '=', fr(fr(sb('P', 'i,t'), sb('N', 't')), fr(ss('P̄', 'i', '0'), ss('N̄', '', '0'))), '×100')],
    numerateur: 'Production par habitant du produit i au cours de l\'année t.',
    denominateur: 'Production moyenne par habitant du produit i au cours de la période de référence.',
    variables: 'Production par produit ; population totale au 1er juillet de chaque année ; moyennes de la période de référence ; poids caloriques de l\'indicateur 1.1.',
    unite: 'Indice (période de référence = 100)',
    frequence: 'Annuelle',
    srcP: 'Statistiques nationales de production ; FAOSTAT (domaine Production) ; population : ANStat (RGPH 2014 et 2021, projections).',
    srcS: 'Nations unies, World Population Prospects ; indice FAOSTAT de production alimentaire nette par habitant (contrôle de cohérence).',
    dispo: 'Productions par produit disponibles dans FAOSTAT pour la Côte d\'Ivoire ; cohérence avec les séries nationales et série de population homogène après le RGPH 2021 : ' + DV.toLowerCase(),
    agregation: 'Moyenne pondérée des indices élémentaires, à poids fixes.',
    ponderations: 'Identiques à celles du taux de couverture (poids caloriques figés).',
    precautions: 'Les produits sans production nationale en période de référence ne peuvent former d\'indice élémentaire ; ils sont exclus de l\'agrégat et les poids restants sont renormalisés selon une règle documentée ; utiliser une série de population rétropolée et homogène.',
    limites: 'Ne tient compte ni des échanges ni des pertes ; sensible aux révisions de la population et aux estimations de production vivrière.',
    comparabilite: 'Même logique que l\'indice FAOSTAT de production alimentaire nette par habitant, mais pondération différente (calories contre prix internationaux) : comparabilité des tendances, non des niveaux.',
    observations: 'Indicateur de capacité productive, à lire avec le taux de couverture.',
    reference: 'FAO, méthodologie des indices de production agricole (FAOSTAT, domaine QI).',
    travaux: 'Valider la série de population ; arrêter la règle applicable aux produits non produits localement ; confronter l\'évolution à l\'indice FAOSTAT.',
  },
  {
    axe: 1, k: 3, code: 'VPROD', dim: 'Résilience du système productif',
    nom: 'Variabilité de la production vivrière par habitant',
    sens: 'Baisse',
    finalite: 'Mesurer la stabilité de la production vivrière par habitant, dimension de résilience du système productif.',
    question: 'La production vivrière par habitant est-elle stable d\'une année à l\'autre autour de sa tendance ?',
    definition: 'Écart type, sur une fenêtre mobile de cinq ans, des écarts entre la série agrégée de production vivrière par habitant (IPVH) et sa tendance.',
    formuleTxt: 'VPROD_{t} = SD(e_{t−4}, …, e_{t}), avec e_{t} = y_{t} − ŷ_{t} et y_{t} = IPVH_{t}',
    math: () => [M(sb('VPROD', 't'), '=SD', '(', sb('e', 't−4'), ',…,', sb('e', 't'), ')', ',   ', sb('e', 't'), '=', sb('y', 't'), '−', sb('ŷ', 't'))],
    numerateur: 'Sans objet (mesure de dispersion).',
    denominateur: 'Sans objet.',
    variables: 'Série IPVH couvrant au moins les quatre années antérieures à la première année calculée ; spécification de la tendance.',
    unite: 'Points d\'indice',
    frequence: 'Annuelle (fenêtre mobile de cinq ans)',
    srcP: 'Série IPVH (indicateur 1.2).',
    srcS: 'FAOSTAT, Suite des indicateurs de la sécurité alimentaire (variabilité de la production alimentaire par habitant), pour contrôle.',
    dispo: 'Dépend de la série IPVH ; une valeur pour 2015 suppose une série 2011-2015 : ' + DV.toLowerCase(),
    agregation: 'Calcul sur la série déjà agrégée (IPVH).',
    ponderations: 'Celles de l\'IPVH.',
    precautions: 'Fixer une fois pour toutes la méthode d\'estimation de la tendance et sa règle de réestimation ; distinguer un choc ponctuel d\'une rupture de tendance.',
    limites: 'Sensible au choix de la tendance et aux révisions de fin de série ; une faible variabilité n\'implique pas un niveau de production suffisant.',
    comparabilite: 'Construit selon la logique de l\'indicateur FAO de variabilité de la production alimentaire par habitant, mais sur une série pondérée en calories.',
    observations: 'À lire conjointement avec l\'IPVH.',
    reference: 'FAO, Suite of Food Security Indicators (FAOSTAT).',
    travaux: 'Arrêter la méthode de tendance ; reconstituer l\'IPVH depuis 2011 ; conduire une analyse de sensibilité.',
  },
  // ───────────────────────── AXE 2
  {
    axe: 2, k: 1, code: 'IP', dim: 'Efficacité productive',
    nom: 'Indice de productivité des cultures à superficie constante',
    sens: 'Hausse',
    finalite: 'Mesurer l\'efficacité productive des cultures, indépendamment de l\'extension des superficies.',
    question: 'Les rendements des principales cultures progressent-ils par rapport à la période de référence ?',
    definition: 'Indice pondéré des rendements (production par hectare récolté) des principales cultures, rapportés à leur niveau de la période de référence, les pondérations étant les parts des cultures dans la valeur de la production végétale de la période de référence.',
    formuleTxt: 'IP_{t} = Σ_{i} w_{i}^{0} × IR_{i,t}, avec IR_{i,t} = R_{i,t} / R_{i,0} × 100 et R_{i,t} = Q_{i,t} / S_{i,t}',
    math: () => [M(sb('IP', 't'), '=', sum('i', [w0(), sb('IR', 'i,t')]), ',   ', sb('IR', 'i,t'), '=', fr(sb('R', 'i,t'), sb('R', 'i,0')), '×100')],
    numerateur: 'Rendement de la culture i au cours de l\'année t.',
    denominateur: 'Rendement de la culture i au cours de la période de référence.',
    variables: 'Production (Q) et superficie récoltée (S) par culture ; superficie en production pour les cultures pérennes ; prix de la période de référence.',
    unite: 'Indice (période de référence = 100)',
    frequence: 'Annuelle',
    srcP: 'Statistiques agricoles nationales (production, superficies) ; FAOSTAT (Production ; valeur de la production agricole).',
    srcS: 'Organes de régulation des filières (café-cacao, coton-anacarde, hévéa-palmier à huile), ADERIZ ; enquêtes de rendement.',
    dispo: 'Productions et superficies disponibles par culture dans FAOSTAT ; qualité des superficies vivrières et des superficies en production des cultures pérennes : ' + DV.toLowerCase(),
    agregation: 'Moyenne pondérée à poids fixes ; équivaut au rapport entre la valeur de la production obtenue avec les superficies de référence et les rendements courants, et la valeur de la période de référence.',
    ponderations: 'Part de chaque culture dans la valeur de la production végétale de la période de référence, à prix constants, figée.',
    precautions: 'Utiliser la superficie en production (et non plantée) pour les cultures pérennes ; recourir à une moyenne mobile pour l\'analyse sans remplacer la série annuelle ; signaler les cultures dont la superficie est estimée par convention.',
    limites: 'Productivité partielle de la terre, qui n\'intègre ni le travail ni les intrants ; sensible aux aléas climatiques ; n\'inclut pas l\'élevage.',
    comparabilite: 'Rendements comparables internationalement culture par culture (FAOSTAT) ; l\'indice agrégé est propre à la pondération nationale.',
    observations: 'La productivité totale des facteurs (USDA ERS) peut être suivie à titre complémentaire.',
    reference: 'Latruffe (2010), OCDE ; FAO, méthodologie des indices de production (Laspeyres).',
    travaux: 'Arrêter la liste des cultures et le système de prix ; documenter la superficie en production des cultures pérennes ; reconstituer les séries 2015-2025.',
  },
  {
    axe: 2, k: 2, code: 'TPR', dim: 'Pertes après récolte',
    nom: 'Taux de pertes post-récolte',
    sens: 'Baisse',
    finalite: 'Mesurer la part de la production perdue entre la récolte et la mise en marché ou l\'entrée en transformation.',
    question: 'Quelle part de la production récoltée est perdue avant d\'atteindre le marché ou l\'unité de transformation ?',
    definition: 'Rapport entre les quantités perdues après la récolte (manutention, stockage, transport, jusqu\'à l\'entrée en transformation ou la mise sur le marché) et la production, agrégé par moyenne pondérée sur les produits suivis.',
    formuleTxt: 'TPR_{t} = Σ_{i} w_{i}^{0} × TPR_{i,t}, avec TPR_{i,t} = Pertes post-récolte_{i,t} / Production_{i,t} × 100',
    math: () => [M(sb('TPR', 't'), '=', sum('i', [w0(), sb('TPR', 'i,t')]), ',   ', sb('TPR', 'i,t'), '=', fr(sb('L', 'i,t'), sb('Q', 'i,t')), '×100')],
    numerateur: 'Pertes quantitatives post-récolte du produit i (L), de la récolte à l\'entrée en transformation ou à la mise en marché.',
    denominateur: 'Production du produit i (Q).',
    variables: 'Pertes quantitatives par produit et par étape ; production ; valeur de la production de la période de référence (pondération).',
    unite: '%',
    frequence: 'Annuelle, avec enquêtes approfondies périodiques',
    srcP: 'Enquêtes nationales de pertes post-récolte ; APHLIS pour les céréales.',
    srcS: 'FAOSTAT (élément « pertes » des bilans alimentaires) ; FAO, indicateur ODD 12.3.1a ; études de filières.',
    dispo: 'Aucune série nationale harmonisée identifiée à ce stade ; estimations APHLIS (céréales) et imputations FAOSTAT à examiner : ' + DV.toLowerCase(),
    agregation: 'Moyenne pondérée à poids fixes.',
    ponderations: 'Recommandation : valeur de la production de la période de référence à prix constants, comme pour l\'indice des pertes alimentaires de la FAO ; variante calorique possible pour une lecture de sécurité alimentaire.',
    precautions: 'Distinguer pertes quantitatives, pertes qualitatives et gaspillage à la consommation ; couvrir les mêmes étapes pour tous les produits.',
    limites: 'Mesure directe coûteuse ; dépendance aux coefficients modélisés ; les pertes qualitatives échappent à l\'indicateur principal.',
    comparabilite: 'Bonne si le périmètre et la pondération suivent l\'indice des pertes alimentaires de la FAO (ODD 12.3.1a).',
    observations: 'Pertes qualitatives suivies en sous-indicateur ; gaspillage hors champ.',
    reference: 'FAO (2019), La situation mondiale de l\'alimentation et de l\'agriculture 2019 ; FAO, métadonnées ODD 12.3.1a ; Affognon et al. (2015).',
    travaux: 'Arrêter les produits et les étapes couverts ; concevoir un dispositif d\'enquête ; arbitrer définitivement la pondération.',
  },
  {
    axe: 2, k: 3, code: 'TT', dim: 'Valeur ajoutée locale',
    nom: 'Taux de transformation nationale des produits agricoles',
    sens: 'Hausse',
    finalite: 'Mesurer la capacité du pays à retenir la valeur ajoutée par la transformation locale de sa production agricole.',
    question: 'Quelle part de la production agricole nationale est transformée en Côte d\'Ivoire ?',
    definition: 'Moyenne pondérée, sur les filières suivies, du rapport entre la quantité de produit national transformée dans le pays à un stade de référence défini par filière et la production nationale disponible pour la transformation.',
    formuleTxt: 'TT_{t} = Σ_{i} w_{i}^{0} × TT_{i,t}, avec TT_{i,t} = QT_{i,t} / QD_{i,t} × 100',
    math: () => [M(sb('TT', 't'), '=', sum('i', [w0(), sb('TT', 'i,t')]), ',   ', sb('TT', 'i,t'), '=', fr(sb('QT', 'i,t'), sb('QD', 'i,t')), '×100')],
    numerateur: 'Quantité de produit i d\'origine nationale transformée en Côte d\'Ivoire au stade de référence (QT), en équivalent matière première.',
    denominateur: 'Production nationale du produit i disponible pour la transformation (QD).',
    variables: 'Quantités transformées localement par filière ; production disponible pour la transformation ; coefficients de conversion ; valeur de la production de référence.',
    unite: '%',
    frequence: 'Annuelle (campagne de commercialisation)',
    srcP: 'Organes de régulation des filières (notamment broyages de cacao et transformation de l\'anacarde) ; ministère chargé de l\'Industrie.',
    srcS: 'ANStat (comptes nationaux, production industrielle) ; statistiques d\'exportation par stade de transformation ; ICCO pour le cacao.',
    dispo: 'Séries de broyage du cacao et de transformation de l\'anacarde publiées par les organes de filière ; profondeur historique homogène 2015-2025 : ' + DV.toLowerCase() + ' Autres filières : ' + DV.toLowerCase(),
    agregation: 'Moyenne pondérée à poids fixes ; publication systématique des taux par filière.',
    ponderations: 'Part de chaque filière dans la valeur de la production agricole de la période de référence.',
    precautions: 'Fixer un stade de transformation de référence par filière ; exprimer les quantités en équivalent matière première ; exclure les matières premières importées ; aligner campagne et année civile.',
    limites: 'Ne mesure ni la profondeur de la transformation ni la valeur ajoutée ; données dispersées pour les filières vivrières et artisanales.',
    comparabilite: 'Faible au niveau agrégé ; bonne par filière (par exemple broyages de cacao rapportés à la production).',
    observations: 'Présenter les résultats par grandes filières dès qu\'ils sont disponibles.',
    reference: 'Barrett et al. (2022), Journal of Economic Literature ; Banque mondiale (2013), Growing Africa.',
    travaux: 'Arrêter la liste des filières et les stades de référence ; fixer les coefficients de conversion ; organiser la collecte auprès des organes de filière.',
  },
  // ───────────────────────── AXE 3
  {
    axe: 3, k: 1, code: 'TCF', dim: 'Satisfaction de la demande exprimée',
    nom: 'Taux de couverture de la demande de financement agricole',
    sens: 'Hausse',
    finalite: 'Mesurer dans quelle mesure la demande formelle de financement agricole est satisfaite par le système financier.',
    question: 'Quelle part des montants de financement agricole formellement demandés est effectivement accordée ?',
    definition: 'Rapport entre le montant des financements agricoles effectivement accordés et le montant total des financements agricoles formellement demandés aux institutions financières formelles au cours de l\'année.',
    formuleTxt: 'TCF_{t} = MA_{t} / MD_{t} × 100',
    math: () => [M(sb('TCF', 't'), '=', fr(sb('MA', 't'), sb('MD', 't')), '×100')],
    numerateur: 'Montant des financements agricoles effectivement accordés au titre des demandes de l\'année t (MA).',
    denominateur: 'Montant total des financements agricoles formellement demandés au cours de l\'année t (MD).',
    variables: 'Montants demandés et accordés, par institution, catégorie d\'acteur, filière et maturité ; nombre de dossiers.',
    unite: '%',
    frequence: 'Annuelle',
    srcP: 'Déclarations périodiques harmonisées des banques et des SFD (dispositif de collecte à instituer).',
    srcS: 'Enquêtes auprès des exploitants (demande, refus, découragement) ; rapports des dispositifs publics de financement.',
    dispo: 'Aucune série publique des montants demandés identifiée : ' + DV.toLowerCase(),
    agregation: 'Rapport de sommes (et non moyenne des ratios par institution).',
    ponderations: 'Implicites, par les montants.',
    precautions: 'Distinguer demande exprimée, demande éligible et besoin total ; rattacher chaque décision à l\'année de la demande ; neutraliser les demandes multiples d\'un même acteur.',
    limites: 'Ignore les emprunteurs découragés ; dépend des pratiques d\'enregistrement des demandes par les institutions.',
    comparabilite: 'Faible : pas de norme internationale.',
    observations: 'Compléter par le taux d\'approbation en nombre de dossiers.',
    reference: 'Stiglitz et Weiss (1981) ; Kon et Storey (2003) ; Boucher, Carter et Guirkinger (2008).',
    travaux: 'Définir « financement agricole » et « demande formelle » ; instituer la collecte ; ajouter un module sur le découragement dans les enquêtes.',
  },
  {
    axe: 3, k: 2, code: 'TAF', dim: 'Accès effectif des acteurs',
    nom: 'Taux d\'accès effectif des acteurs agricoles au financement formel',
    sens: 'Hausse',
    finalite: 'Mesurer l\'étendue de l\'accès effectif des acteurs agricoles au financement formel.',
    question: 'Quelle proportion des acteurs agricoles a effectivement obtenu un financement formel au cours des douze derniers mois ?',
    definition: 'Proportion des acteurs agricoles (exploitations et entreprises agricoles) ayant obtenu au moins un financement auprès d\'une institution formelle réglementée au cours des douze derniers mois.',
    formuleTxt: 'TAF_{t} = NF_{t} / NA_{t} × 100',
    math: () => [M(sb('TAF', 't'), '=', fr(sb('NF', 't'), sb('NA', 't')), '×100')],
    numerateur: 'Nombre d\'acteurs agricoles ayant obtenu au moins un financement formel au cours des douze derniers mois (NF), sans double compte.',
    denominateur: 'Nombre total d\'acteurs agricoles (NA).',
    variables: 'Acteurs financés par type d\'institution ; nombre total d\'acteurs ; ventilations par sexe, taille, filière et région.',
    unite: '%',
    frequence: 'Annuelle ou selon la périodicité des enquêtes',
    srcP: 'Enquêtes auprès des ménages et des exploitations (EHCVM, enquêtes agricoles) ; REEA 2015-2016 pour le dénominateur.',
    srcS: 'Données administratives des banques et SFD (nombre d\'emprunteurs agricoles) ; Global Findex (Banque mondiale) pour le contexte.',
    dispo: 'Pas de série annuelle identifiée ; points d\'enquête ponctuels à exploiter : ' + DV.toLowerCase(),
    agregation: 'Rapport d\'effectifs, avec pondérations de sondage.',
    ponderations: 'Pondérations de sondage des enquêtes.',
    precautions: 'Ne pas assimiler possession d\'un compte, usage du mobile money ou inclusion financière générale à l\'accès au financement agricole ; exclure de l\'indicateur principal le crédit fournisseur, le crédit informel et les avances non réglementées.',
    limites: 'Hétérogénéité des unités (ménage, exploitation, entreprise) ; dénominateur recensé à une date ancienne ; acteurs financés par plusieurs institutions.',
    comparabilite: 'Partielle : le Global Findex mesure l\'emprunt auprès d\'une institution formelle, tous usages confondus.',
    observations: 'Le financement de filière non réglementé est suivi à titre complémentaire.',
    reference: 'Christen et Anderson (2013), CGAP Focus Note 85 ; Banque mondiale, Global Findex.',
    travaux: 'Arrêter l\'unité statistique ; intégrer un module harmonisé dans les enquêtes nationales ; actualiser le dénominateur.',
  },
  {
    axe: 3, k: 3, code: 'PMLT', dim: 'Adéquation à l\'investissement',
    nom: 'Part des financements agricoles à moyen et long terme',
    sens: 'Hausse',
    finalite: 'Mesurer l\'adaptation du financement agricole aux besoins d\'investissement productif.',
    question: 'Quelle part du crédit agricole finance des besoins de moyen et long terme ?',
    definition: 'Part des crédits à moyen et long terme dans le total des crédits accordés aux activités agricoles.',
    formuleTxt: 'PMLT_{t} = (CMT_{t} + CLT_{t}) / CT_{t} × 100',
    math: () => [M(sb('PMLT', 't'), '=', fr([sb('CMT', 't'), '+', sb('CLT', 't')], sb('CT', 't')), '×100')],
    numerateur: 'Crédits agricoles à moyen terme (CMT) et à long terme (CLT).',
    denominateur: 'Crédits agricoles totaux, tous termes confondus (CT).',
    variables: 'Encours (ou mises en place) de crédits par secteur d\'activité et par terme ; données des SFD.',
    unite: '%',
    frequence: 'Annuelle (données infra-annuelles disponibles)',
    srcP: 'BCEAO, Centrale des risques : utilisations de crédits déclarées par secteur d\'activité et par terme (Bulletin mensuel des statistiques).',
    srcS: 'Base de données EDEN de la BCEAO ; données prudentielles et statistiques des SFD.',
    dispo: 'Tableaux par secteur et par terme publiés par la BCEAO pour la Côte d\'Ivoire ; profondeur historique homogène 2015-2025 : ' + DV.toLowerCase(),
    agregation: 'Rapport de sommes.',
    ponderations: 'Sans objet.',
    precautions: 'Ne pas mélanger encours et mises en place ; retenir la nomenclature sectorielle de la BCEAO et documenter les branches incluses ; tenir compte du seuil de déclaration.',
    limites: 'La Centrale des risques ne couvre pas les crédits inférieurs au seuil de déclaration ni l\'ensemble des SFD ; le crédit aux exportateurs et aux agro-industries peut être classé hors agriculture.',
    comparabilite: 'Bonne au sein de l\'UEMOA (nomenclature commune de la BCEAO).',
    observations: 'Série la plus directement reconstituable de l\'axe 3.',
    reference: 'BCEAO, Bulletin mensuel des statistiques (Centrale des risques).',
    travaux: 'Extraire les séries par secteur et par terme ; vérifier les définitions des termes et le seuil de déclaration ; intégrer les SFD.',
  },
  // ───────────────────────── AXE 4
  {
    axe: 4, k: 1, code: 'TCDF', dim: 'Sécurisation des parcelles',
    nom: 'Taux de couverture du domaine foncier rural par des droits fonciers formalisés',
    sens: 'Hausse',
    finalite: 'Mesurer l\'avancement de la formalisation des droits sur les terres du domaine foncier rural.',
    question: 'Quelle part du domaine foncier rural est couverte par des droits fonciers formalisés ?',
    definition: 'Rapport entre la superficie cumulée, sans double compte, des terres couvertes par un acte de formalisation admissible (certificat foncier individuel ou collectif, titre foncier) et la superficie totale du domaine foncier rural.',
    formuleTxt: 'TCDF_{t} = SDF_{t} / SDFR × 100',
    math: () => [M(sb('TCDF', 't'), '=', fr(sb('SDF', 't'), 'SDFR'), '×100')],
    numerateur: 'Superficie cumulée couverte par des droits fonciers formalisés (SDF), chaque parcelle étant comptée une seule fois.',
    denominateur: 'Superficie totale du domaine foncier rural (SDFR), fixée par convention.',
    variables: 'Registre parcellaire avec identifiant unique, superficie et statut juridique de chaque parcelle ; superficie de référence du domaine foncier rural.',
    unite: '%',
    frequence: 'Annuelle (stock au 31 décembre)',
    srcP: 'AFOR, Système d\'information foncière rurale (SIFOR).',
    srcS: 'Services de la conservation foncière (titres issus de l\'immatriculation) ; ObservaTerra.',
    dispo: 'Bilans de délivrance publiés par l\'AFOR ; séries annuelles de superficies certifiées 2015-2025 : ' + DV.toLowerCase(),
    agregation: 'Somme des superficies par parcelle, sur la base d\'un identifiant unique.',
    ponderations: 'Sans objet.',
    precautions: 'Définir limitativement les actes admissibles ; éviter le double compte lors de la conversion d\'un certificat en titre ; préciser le traitement des certificats dont la validité serait échue.',
    limites: 'La formalisation ne garantit pas la sécurité perçue ; les mutations ultérieures doivent être tenues à jour ; le dénominateur doit être fixé officiellement.',
    comparabilite: 'Conceptuellement proche du volet documentaire de l\'ODD 1.4.2, mais mesuré en superficie et non en population.',
    observations: 'Ventiler par type de certificat (individuel, collectif) et selon le sexe des titulaires.',
    reference: 'Loi n° 98-750 modifiée ; FAO (2012), Directives volontaires ; Lawry et al. (2017).',
    travaux: 'Arrêter la liste des actes admissibles ; fixer la superficie de référence ; extraire les séries du SIFOR.',
  },
  {
    axe: 4, k: 2, code: 'TDV', dim: 'Sécurisation des territoires',
    nom: 'Taux de délimitation juridiquement achevée des territoires villageois',
    sens: 'Hausse',
    finalite: 'Mesurer la sécurisation des territoires villageois, préalable à la certification des parcelles.',
    question: 'Quelle part des villages dispose d\'un territoire dont la délimitation est juridiquement achevée ?',
    definition: 'Proportion des villages officiels dont la délimitation du territoire a été consacrée par l\'acte administratif définitif prévu par la réglementation en vigueur.',
    formuleTxt: 'TDV_{t} = VDJ_{t} / VO_{t} × 100',
    math: () => [M(sb('TDV', 't'), '=', fr(sb('VDJ', 't'), sb('VO', 't')), '×100')],
    numerateur: 'Nombre de villages dont la délimitation est juridiquement achevée (VDJ).',
    denominateur: 'Nombre total de villages officiels (VO).',
    variables: 'Liste officielle des villages ; statut de chaque village à chaque étape de la procédure ; date de l\'acte définitif.',
    unite: '%',
    frequence: 'Annuelle',
    srcP: 'AFOR (SIFOR) ; actes de consécration de la délimitation.',
    srcS: 'Ministère chargé de l\'Intérieur (liste officielle des villages) ; ObservaTerra.',
    dispo: 'Bilans d\'étape publiés par l\'AFOR ; série annuelle distinguant les étapes de la procédure : ' + DV.toLowerCase(),
    agregation: 'Comptage.',
    ponderations: 'Sans objet ; variante pondérée par la superficie en complément.',
    precautions: 'Ne pas assimiler territoire bouclé-borné et délimitation juridiquement achevée ; suivre les étapes intermédiaires comme sous-indicateurs.',
    limites: 'Chaque village compte pour une unité quelle que soit sa superficie ; des contestations de limites peuvent subsister.',
    comparabilite: 'Propre au droit ivoirien.',
    observations: 'Publier l\'entonnoir des étapes en complément du tableau de bord.',
    reference: 'Décret n° 2019-263 du 27 mars 2019 ; décret n° 2024-850 du 30 septembre 2024 ; PNSFR 2023-2033.',
    travaux: 'Confirmer l\'acte définitif dans la procédure en vigueur ; figer la liste des villages ; reconstituer l\'historique par étape.',
  },
  {
    axe: 4, k: 3, code: 'TFR', dim: 'Sécurisation des relations d\'exploitation',
    nom: 'Taux de formalisation des relations foncières d\'exploitation',
    sens: 'Hausse',
    finalite: 'Mesurer la sécurisation des relations entre détenteurs de droits et exploitants non propriétaires.',
    question: 'Quelle part des relations d\'exploitation par des non-propriétaires est couverte par un contrat écrit enregistré ?',
    definition: 'Proportion des relations d\'exploitation de terres rurales par un non-propriétaire (location, prêt, droits d\'usage, planter-partager et autres formes reconnues) couvertes par un contrat écrit enregistré.',
    formuleTxt: 'TFR_{t} = RCE_{t} / RNP_{t} × 100',
    math: () => [M(sb('TFR', 't'), '=', fr(sb('RCE', 't'), sb('RNP', 't')), '×100')],
    numerateur: 'Nombre de relations d\'exploitation non-propriétaire couvertes par un contrat écrit enregistré (RCE).',
    denominateur: 'Nombre total de relations d\'exploitation non-propriétaire identifiées (RNP).',
    variables: 'Contrats enregistrés par type ; relations d\'exploitation identifiées lors des opérations foncières ou des enquêtes.',
    unite: '%',
    frequence: 'Annuelle (numérateur) ; dénominateur selon les enquêtes',
    srcP: 'AFOR (SIFOR) pour les contrats enregistrés ; enquêtes des opérations de sécurisation foncière.',
    srcS: 'Recensement et enquêtes agricoles (mode de faire-valoir) ; études de terrain.',
    dispo: 'Nombre de contrats signés publié ponctuellement par l\'AFOR ; dénominateur non disponible en série : ' + DV.toLowerCase(),
    agregation: 'Comptage, ventilé par type de relation.',
    ponderations: 'Sans objet.',
    precautions: 'Définir précisément « enregistré » ; retenir comme unité le couple parcelle-exploitant ; ne pas compter deux fois un renouvellement.',
    limites: 'Dénominateur difficile à observer ; contrats écrits non enregistrés exclus.',
    comparabilite: 'Faible, indicateur propre au contexte ivoirien.',
    observations: 'Indicateur transitoire possible : nombre cumulé de contrats enregistrés, sans remplacer l\'indicateur principal.',
    reference: 'Colin (2013), Land Use Policy, 31 ; FAO (2012), Directives volontaires.',
    travaux: 'Arrêter la typologie des relations ; estimer le dénominateur par enquête ; reconstituer la série des contrats.',
  },
  // ───────────────────────── AXE 5
  {
    axe: 5, k: 1, code: 'PAD', dim: 'Pratiques de production',
    nom: 'Part de la superficie agricole sous pratiques de production durable',
    sens: 'Hausse',
    finalite: 'Mesurer la diffusion de modes de production qui préservent les ressources productives.',
    question: 'Quelle part de la superficie agricole est conduite selon des pratiques reconnues comme durables ?',
    definition: 'Rapport entre la superficie agricole sur laquelle au moins une pratique inscrite sur une liste nationale harmonisée est effectivement appliquée et la superficie agricole totale.',
    formuleTxt: 'PAD_{t} = SPD_{t} / SAT_{t} × 100',
    math: () => [M(sb('PAD', 't'), '=', fr(sb('SPD', 't'), sb('SAT', 't')), '×100')],
    numerateur: 'Superficie agricole sous au moins une pratique reconnue (SPD), chaque parcelle étant comptée une fois.',
    denominateur: 'Superficie agricole totale (SAT), selon le périmètre retenu.',
    variables: 'Pratiques appliquées par parcelle et superficies correspondantes ; superficie agricole totale.',
    unite: '%',
    frequence: 'Annuelle ou selon la périodicité des enquêtes',
    srcP: 'Enquêtes agricoles avec module « pratiques » ; registres de la norme ARS 1000 et des certifications.',
    srcS: 'ANADER, programmes et projets ; télédétection (agroforesterie) ; dispositif ODD 2.4.1.',
    dispo: 'Pas de série nationale harmonisée identifiée : ' + DV.toLowerCase(),
    agregation: 'Union des superficies (et non somme des superficies par pratique).',
    ponderations: 'Sans objet.',
    precautions: 'Adopter une liste nationale harmonisée et des critères minimaux d\'application ; compter chaque parcelle une seule fois.',
    limites: 'La présence d\'une pratique ne garantit pas un résultat environnemental ; données dispersées entre projets.',
    comparabilite: 'Partielle avec l\'ODD 2.4.1, qui repose sur des seuils de durabilité évalués par exploitation.',
    observations: 'Superficies par pratique suivies en sous-indicateurs.',
    reference: 'FAO, métadonnées de l\'ODD 2.4.1 ; Pretty et al. (2018), Nature Sustainability.',
    travaux: 'Arrêter la liste des pratiques et les critères ; concevoir le module d\'enquête ; fixer le périmètre du dénominateur.',
  },
  {
    axe: 5, k: 2, code: 'TDA', dim: 'Préservation des forêts',
    nom: 'Taux de déforestation imputable à l\'expansion agricole',
    sens: 'Baisse',
    finalite: 'Mesurer la pression de l\'expansion agricole sur les forêts.',
    question: 'Quelle part de la forêt existante est convertie chaque année en terres agricoles ?',
    definition: 'Rapport entre la superficie forestière convertie en terres agricoles au cours de la période et la superficie forestière au début de la période.',
    formuleTxt: 'TDA_{t} = SFA_{t} / SF_{t−1} × 100',
    math: () => [M(sb('TDA', 't'), '=', fr(sb('SFA', 't'), sb('SF', 't−1')), '×100')],
    numerateur: 'Superficie forestière dont l\'usage final est agricole (SFA), en déforestation brute.',
    denominateur: 'Superficie forestière au début de la période (SF).',
    variables: 'Cartes d\'occupation des terres à deux dates au moins ; matrice de changement par usage final ; définition nationale de la forêt.',
    unite: '% par an',
    frequence: 'Annuelle, ou annualisée à partir de cartes périodiques',
    srcP: 'Cartographie nationale de l\'occupation des terres (BNETD-CCT, SEP-REDD+, ministère chargé des Eaux et Forêts).',
    srcS: 'FAO FRA ; Global Forest Watch (Hansen et al.) ; JRC TMF ; cartes du cacao (Kalischek et al., 2023).',
    dispo: 'Produits satellitaires annuels couvrant la Côte d\'Ivoire (perte de couvert arboré depuis 2001 ; forêts tropicales humides du JRC depuis 1990) ; attribution nationale par usage final : ' + DV.toLowerCase(),
    agregation: 'Somme sur le territoire national.',
    ponderations: 'Sans objet.',
    precautions: 'Appliquer la définition nationale de la forêt ; mesurer une déforestation brute ; distinguer les causes ; fixer une règle de classement de l\'agroforesterie cacaoyère.',
    limites: 'Confusion possible entre couvert arboré et forêt ; incertitude sur l\'attribution des causes ; décalage de détection.',
    comparabilite: 'Bonne si la définition FAO et des produits satellitaires communs sont utilisés.',
    observations: 'Objectif de long terme : découpler croissance de la production agricole et conversion forestière.',
    reference: 'FAO (2020), FRA 2020 ; Curtis et al. (2018) ; Pendrill et al. (2022) ; Puyravaud (2003).',
    travaux: 'Arrêter la définition et la source de référence ; produire la matrice de changement ; fixer la règle d\'annualisation.',
  },
  {
    axe: 5, k: 3, code: 'IC', dim: 'Empreinte climatique',
    nom: 'Intensité des émissions de gaz à effet de serre de la production agricole',
    sens: 'Baisse',
    finalite: 'Mesurer l\'efficacité climatique de la production agricole.',
    question: 'Quelle quantité de gaz à effet de serre la production agricole émet-elle par unité de valeur produite ?',
    definition: 'Rapport entre les émissions de gaz à effet de serre de l\'agriculture, hors changement d\'affectation des terres, et la valeur réelle de la production agricole ou, selon la série la plus robuste, la valeur ajoutée agricole réelle.',
    formuleTxt: 'IC_{t} = E_{t} / V_{t}, où V_{t} est la valeur réelle de la production agricole ou la valeur ajoutée agricole réelle',
    math: () => [M(sb('IC', 't'), '=', fr(sb('E', 't'), sb('V', 't')))],
    numerateur: 'Émissions agricoles « à la ferme » (E) : fermentation entérique, gestion des déjections, riziculture, sols agricoles et engrais, brûlage des résidus, autres sources agricoles de l\'inventaire, en tCO₂e.',
    denominateur: 'Valeur réelle de la production agricole ou valeur ajoutée agricole réelle (V), en millions de FCFA constants.',
    variables: 'Émissions par source et par gaz ; potentiels de réchauffement global ; valeur de la production ou valeur ajoutée à prix constants.',
    unite: 'tCO₂e par million de FCFA constants',
    frequence: 'Annuelle',
    srcP: 'Inventaire national des gaz à effet de serre (secteur agriculture), communiqué à la CCNUCC.',
    srcS: 'FAOSTAT (Émissions totales ; indicateurs d\'émissions) ; ANStat (comptes nationaux).',
    dispo: 'FAOSTAT publie pour la Côte d\'Ivoire les émissions agricoles et une intensité par valeur de production ; série d\'inventaire national annuelle et homogène : ' + DV.toLowerCase(),
    agregation: 'Rapport de sommes.',
    ponderations: 'Sans objet (potentiels de réchauffement fixes).',
    precautions: 'Exclure les émissions liées au changement d\'affectation des terres ; retenir un jeu unique de potentiels de réchauffement ; aligner le périmètre du numérateur et du dénominateur ; raisonner à prix constants.',
    limites: 'Émissions souvent estimées avec des facteurs par défaut peu sensibles aux pratiques ; effets de prix et de composition sur le dénominateur ; une baisse de l\'intensité peut coexister avec une hausse des émissions absolues.',
    comparabilite: 'Bonne via FAOSTAT (émissions par valeur de production agricole).',
    observations: 'Dénominateur définitif à arrêter selon la robustesse des séries ; émissions absolues suivies en complément.',
    reference: 'GIEC (2006, 2019) ; Tubiello et al. (2013) ; FAOSTAT, note méthodologique des indicateurs d\'émissions.',
    travaux: 'Arrêter le dénominateur ; rapprocher inventaire national et FAOSTAT ; fixer les potentiels de réchauffement.',
  },
];

module.exports = { AXES, IND, DV };
